[package]
name = "dkv"
version = "0.1.0"
edition = "2021"

[dependencies]
dkv_db = { path = "../db" }
tokio = { version = "*", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
