name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose

    - name: Start dkv
      run: cargo run --bin dkv

    - uses: actions/checkout@v4
      with:
        name: tair-opensource/compatibility-test-suite-for-redis
        path: copatibility-test-suite-for-redis
    - name: Build compatibility-test-suite-for-redis
      run: python3 -m pip install -r requirements.txt
      working-directory: compatibility-test-suite-for-redis
    - name: Run comptibility test
      run: python3 redis_compatibility_test.py --port 6543 --testfile cts.json
      working-directory: compatibility-test-suite-for-redis

